xiva-daemon-python-configs (1.4.1-1) unstable; urgency=low

  * Initial release

 -- ponomarev <ponomarev@yandex-team.ru>  Mon, 22 Nov 2010 18:25:28 +0300
